### ISSUE TITLE
InternalError: Unhandled Exception

### ISSUE THREAD

**Issue by Hiro2195** [juzeon/SydneyQt#118]
Traceback (most recent call last):
  File "main.py", line 571, in send_sydney
    await stream_output()
  File "main.py", line 493, in stream_output
    async for response in agen:
  File "sydney.py", line 385, in ask_stream
    raise Exception(
Exception: InternalError: Unhandled Exception

**Comment by juzeon** [comment]
Retry or set a usable proxy according to FAQ if necessary.
