### ISSUE TITLE
可以正常打开，但无法使用

### ISSUE THREAD

**Issue by wuxin008** [juzeon/SydneyQt#129]
软件显示：”错误：无法识别当前用户，检查cookies是否过期”。v1的python显示错误代码TooManyRedirects：
```
Traceback (most recent call last):
  File "D:\download\SydneyQt-1\main.py", line 460, in send_sydney
    conversation = await sydney.create_conversation(cookies=cookies, proxy=proxy if proxy != "" else None)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\download\SydneyQt-1\sydney.py", line 225, in create_conversation
    response = await session.get(
               ^^^^^^^^^^^^^^^^^^
  File "C:\Python311\Lib\site-packages\aiohttp\client.py", line 629, in _request
    raise TooManyRedirects(
aiohttp.client_exceptions.TooManyRedirects: 0, message='', url=URL('https://edgeservices.bing.com/edgesvc/turing/conversation/create')
```
在调试过程中可以正常和Bing AI聊天，无论如何重新导入cookies均不奏效。cookies到处使用的是Edge的Cookie-Editor。

**Comment by wuxin008** [comment]
已解决，问题同#91.
