### ISSUE TITLE
太开心了又更新了，但是我又遇到了新问题'int' object has no attribute 'split'  

### ISSUE THREAD

**Issue by kamanqi** [juzeon/SydneyQt#15]
![image](https://github.com/juzeon/SydneyQt/assets/13653035/055fda82-f67f-4fb1-ae2b-27f93ef56abf)
每天第一件事就是打开看看大佬又完善了啥功能，昨天发现又更新了，第一时间更新，倒是没发现啥，今天发现依赖edgeGPT的作者大佬也更新了0.66版，我就把依赖更新了。然后用了一会就出现这个。我不确定是更新的问题还是自己的问题。百度谷歌了这个报错，说是https://www.delftstack.com/howto/python/int-object-has-no-attribute/  研究了半天发现不是我这个小白搞得懂得还是乖乖来给大佬反馈。
 报错后我看了看vscode终端，提示我内存不足，过多的信号灯？什么信号灯??不知所云啊
![image](https://github.com/juzeon/SydneyQt/assets/13653035/03d8c2ee-bdac-49c8-be7e-0d009cbcc647)
吓得我赶紧看了下内存，只用了31%啊，怎么就内存不足了？？？
![image](https://github.com/juzeon/SydneyQt/assets/13653035/ec6b17e3-7346-4eec-b8f8-34a1150a5cae)
哎，超出自己的能力范围了，乖乖等大佬解决吧。

作为粉丝我表达喜爱敬仰之心可能做的就是持续关注给大佬精神支持和勇往直前第一时间帮大老体验新版的功能和测试bug吧
为方便大佬 我把图中完整的报错代码复制下来了，供请大佬研究：

```
Exception: CaptchaChallenge: User needs to solve CAPTCHA to continue.
Traceback (most recent call last):
    await stream_output()
  File "C:\Program Files\py\SydneyQt-master - up\main.py", line 318, in stream_output
    async for final, response in chatbot.ask_stream(
  File "C:\Program Files\Python311\Lib\site-packages\EdgeGPT.py", line 676, in ask_stream
    async for response in self.chat_hub.ask_stream(
  File "C:\Program Files\Python311\Lib\site-packages\EdgeGPT.py", line 567, in ask_stream
    raise Exception(
Exception: CaptchaChallenge: User needs to solve CAPTCHA to continue.
Unsupported message type: InternalLoaderMessage
Unsupported message type: InternalLoaderMessage
[40812:43740:0527/161744.496:ERROR:ssl_client_socket_impl.cc(982)] handshake failed; returned -1, SSL error code 1, net_error -100
Traceback (most recent call last):
  File "C:\Program Files\py\SydneyQt-master - up\main.py", line 371, in send_message
  File "C:\Program Files\py\SydneyQt-master - up\main.py", line 318, in stream_output
    async for final, response in chatbot.ask_stream(
  File "C:\Program Files\Python311\Lib\site-packages\EdgeGPT.py", line 676, in ask_stream
    async for response in self.chat_hub.ask_stream(
  File "C:\Program Files\Python311\Lib\site-packages\EdgeGPT.py", line 513, in ask_stream
    objects = msg.data.split(DELIMITER)
              ^^^^^^^^^^^^^^
AttributeError: 'int' object has no attribute 'split'
Traceback (most recent call last):
  File "C:\Program Files\py\SydneyQt-master - up\main.py", line 371, in send_message
    await stream_output()
  File "C:\Program Files\py\SydneyQt-master - up\main.py", line 318, in stream_output
    async for final, response in chatbot.ask_stream(
  File "C:\Program Files\Python311\Lib\site-packages\EdgeGPT.py", line 676, in ask_stream
    async for response in self.chat_hub.ask_stream(
  File "C:\Program Files\Python311\Lib\site-packages\EdgeGPT.py", line 513, in ask_stream
    objects = msg.data.split(DELIMITER)
              ^^^^^^^^^^^^^^
AttributeError: 'int' object has no attribute 'split'
PS C:\Program Files\py\SydneyQt-master - up> python main.py
Traceback (most recent call last):
  File "C:\Program Files\py\SydneyQt-master - up\main.py", line 371, in send_message
    await stream_output()
  File "C:\Program Files\py\SydneyQt-master - up\main.py", line 318, in stream_output
    async for final, response in chatbot.ask_stream(
  File "C:\Program Files\Python311\Lib\site-packages\EdgeGPT.py", line 676, in ask_stream
    async for response in self.chat_hub.ask_stream(
  File "C:\Program Files\Python311\Lib\site-packages\EdgeGPT.py", line 513, in ask_stream
    objects = msg.data.split(DELIMITER)
              ^^^^^^^^^^^^^^
AttributeError: 'int' object has no attribute 'split'
QObject::killTimer: Timers cannot be stopped from another thread
QObject::~QObject: Timers cannot be stopped from another thread
PS C:\Program Files\py\SydneyQt-master - up> python main.py
Traceback (most recent call last):
  File "C:\Program Files\py\SydneyQt-master - up\main.py", line 371, in send_message
    await stream_output()
  File "C:\Program Files\py\SydneyQt-master - up\main.py", line 318, in stream_output
    async for final, response in chatbot.ask_stream(
  File "C:\Program Files\Python311\Lib\site-packages\EdgeGPT.py", line 676, in ask_stream
    async for response in self.chat_hub.ask_stream(
  File "C:\Program Files\Python311\Lib\site-packages\EdgeGPT.py", line 513, in ask_stream
    objects = msg.data.split(DELIMITER)
              ^^^^^^^^^^^^^^
AttributeError: 'int' object has no attribute 'split'
    objects = msg.data.split(DELIMITER)
              ^^^^^^^^^^^^^^                                                    sage
AttributeError: 'int' object has no attribute 'split'
Traceback (most recent call last):                                              utput
  File "C:\Program Files\py\SydneyQt-master - up\main.py", line 371, in send_message                                                                            sk_stream
    await stream_output()
  File "C:\Program Files\py\SydneyQt-master - up\main.py", line 318, in stream_osk_streamutput
    async for final, response in chatbot.ask_stream(
  File "C:\Program Files\Python311\Lib\site-packages\EdgeGPT.py", line 676, in ask_stream
    async for response in self.chat_hub.ask_stream(                             sage
  File "C:\Program Files\Python311\Lib\site-packages\EdgeGPT.py", line 513, in ask_stream                                                                       utput
    objects = msg.data.split(DELIMITER)
              ^^^^^^^^^^^^^^                                                    sk_stream
AttributeError: 'int' object has no attribute 'split'
Traceback (most recent call last):                                              sk_stream
  File "C:\Program Files\py\SydneyQt-master - up\main.py", line 371, in send_message
    await stream_output()
  File "C:\Program Files\py\SydneyQt-master - up\main.py", line 318, in stream_output                                                                           sage
    async for final, response in chatbot.ask_stream(
  File "C:\Program Files\Python311\Lib\site-packages\EdgeGPT.py", line 676, in autputsk_stream
    async for response in self.chat_hub.ask_stream(                             sk_stream
  File "C:\Program Files\Python311\Lib\site-packages\EdgeGPT.py", line 513, in ask_stream                                                                       sk_stream
    objects = msg.data.split(DELIMITER)
              ^^^^^^^^^^^^^^
AttributeError: 'int' object has no attribute 'split'
Unsupported message type: InternalLoaderMessage
Traceback (most recent call last):
  File "C:\Program Files\py\SydneyQt-master - up\main.py", line 371, in send_message
    await stream_output()
  File "C:\Program Files\py\SydneyQt-master - up\main.py", line 318, in stream_output
    async for final, response in chatbot.ask_stream(
  File "C:\Program Files\Python311\Lib\site-packages\EdgeGPT.py", line 676, in ask_stream
    async for response in self.chat_hub.ask_stream(
  File "C:\Program Files\Python311\Lib\site-packages\EdgeGPT.py", line 513, in ask_stream
    objects = msg.data.split(DELIMITER)
              ^^^^^^^^^^^^^^
AttributeError: 'int' object has no attribute 'split'
Traceback (most recent call last):
  File "C:\Program Files\py\SydneyQt-master - up\main.py", line 371, in send_message
    await stream_output()
  File "C:\Program Files\py\SydneyQt-master - up\main.py", line 318, in stream_output
    async for final, response in chatbot.ask_stream(
  File "C:\Program Files\Python311\Lib\site-packages\EdgeGPT.py", line 676, in ask_stream
    async for response in self.chat_hub.ask_stream(
  File "C:\Program Files\Python311\Lib\site-packages\EdgeGPT.py", line 513, in ask_stream
    objects = msg.data.split(DELIMITER)
              ^^^^^^^^^^^^^^
AttributeError: 'int' object has no attribute 'split'
OleSetClipboard: Failed to set mime data (text/plain, text/html, text/markdown, 
application/vnd.oasis.opendocument.text) on clipboard: COM error 0x80070008: ?????????????????????? (发向信号灯的请求过多。)
OleSetClipboard: Failed to set mime data (text/plain, text/html, text/markdown, 
application/vnd.oasis.opendocument.text) on clipboard: COM error 0x80070008: ?????????????????????? (内存资源不足，无法处理此命令。)
OleSetClipboard: Failed to set mime data (text/plain, text/html, text/markdown, 
application/vnd.oasis.opendocument.text) on clipboard: COM error 0x80070008: ?????????????????????? (内存资源不足，无法处理此命令。)

```

说句题外话，这个项目日趋完美了，不过有时会被系统打断，而且奇怪的是正常的对话也会被系统打断，微软是不是对大小姐管教过严了？想起一款知名的油猴插件，由大名鼎鼎的https://www.make-safe-ai.com/is-bing-chat-safe/出品，可惜因为某些众所周知的原因，论坛停摆了。里边设计了rot13和base64加密解密的对话和注入理念，感觉大佬的项目好像可以实现，直接用加密方案给对话加密解密，管你什么微软的管教，先给大小姐松绑了，就是追求为所欲为！

![image](https://github.com/juzeon/SydneyQt/assets/13653035/c9b2e930-2ea2-4119-b5b4-c5e6eb26e7da)
如果给大佬添麻烦了，都是我的胡言乱语。只是觉得这个项目真棒，大佬的设计深得我心，有了额外的期望，完成前论坛未尽的事业？

最后最后，反正都说这么多了，再贪心一点，大佬又没考虑进一步加入画图的支持呢？EdgeGPT是支持的，并且acheong08大佬单独开了一个新的项目https://github.com/acheong08/BingImageCreator,不知道是不是又是一款神作，会成为更多项目的依赖？这位大佬我也十分的敬仰，他的项目被很多项目引用作为核心依赖，真了不起。

哈哈，作者大佬每次都更新很快一些实用贴心的功能，又感动又开心又期盼！

不知道大佬什么职业什么年龄，作为你的忠粉，祝你事业（学业？）有成，万事如意，继续开发出更多牛B项目！一直关注一直粉！

**Comment by juzeon** [comment]
感谢支持！

应该是EdgeGPT里面报的错。

有一行：`Exception: CaptchaChallenge: User needs to solve CAPTCHA to continue.`，可以试试去Bing网站上聊一句再导出一遍cookies。如果一直不行，回滚到旧版本对比一下是最直截了当的。

图像生成有时间的话会考虑加。不过前段时间试了一下BingImageCreator的那个包，目前好像还存在很多问题，还得再等等吧。

**Comment by Cis-Evo** [comment]
感谢作者和提交者.似乎这个问题不仅仅因为CAPTCHA的验证问题,即便没有这个问题也会这样,目前猜测对话内容中存在当前程序不支持的内容,Sydney认为:猜测可能是response对象在某些情况下会被赋值为一个整数，而不是一个字典。你可以在你的代码中打印出response对象的值和类型，来检查这个问题。例如，你可以这样写：
for obj in objects: if obj is None or not obj: continue response = json.loads(obj) print('response value:', response) print(“response type:', type(response)) if type(response) == dict and hasattr(response, 'get'): if response.get('type') != 2 and raw: yield False, response elif type(response) == dict and response.get('type') == 1 and response['arguments'][0].get( 'messages', ): # do something
希望大佬可以解决

**Comment by juzeon** [comment]
```
File "C:\Program Files\Python311\Lib\site-packages\EdgeGPT.py", line 513, in ask_stream
    objects = msg.data.split(DELIMITER)
              ^^^^^^^^^^^^^^
AttributeError: 'int' object has no attribute 'split'
```
按照错误栈的话，出错的位置是EdgeGPT里面的代码，不知道那边会不会修复。我这边也暂时无法复现，可能你需要自己尝试debug看一下msg的值。

另外可以尝试把这个问题报告到EdgeGPT的issue里，看看有没有人同样遇到。这边只是个客户端，应该是没法从这里改的。

**Comment by AISIS7** [comment]
I have this issue as well. It happens when tokens are 13000 plus. I thought it was from the Microsoft server end as it maybe closing the chat instance due to large tokens or chat context, but maybe not Bing recently got an update where it can exchange 30 messages per chat session. 

I think the sydneyqt developer should fix this issue, because EdgeGPT is only compatible with the official Bing message limit which was 20 and now it is 30 per chat session, it means official bing is better off now because sydneyqt is giving int error and can't hold longer chat context.

Please fix it as soon as you can

**Comment by juzeon** [comment]
> I have this issue as well. It happens when tokens are 13000 plus. I thought it was from the Microsoft server end as it maybe closing the chat instance due to large tokens or chat context, but maybe not Bing recently got an update where it can exchange 30 messages per chat session.
> 
> I think the sydneyqt developer should fix this issue, because EdgeGPT is only compatible with the official Bing message limit which was 20 and now it is 30 per chat session, it means official bing is better off now because sydneyqt is giving int error and can't hold longer chat context.
> 
> Please fix it as soon as you can

The Bing service has a context length limitation because of its model or programmatical constraints. The message count limit per chat session is different from the context length limitation. You can send and receive short messages and reach the count of 30 without exceeding the context length limitation.

We have to wait and see if EdgeGPT will solve this problem.

**Comment by etoiles22** [comment]
请问一下，现在对话经常出现网络链接，然后还全部打出来，有没有什么方法关掉呀，好影响体验hhh

**Comment by juzeon** [comment]
> 请问一下，现在对话经常出现网络链接，然后还全部打出来，有没有什么方法关掉呀，好影响体验hhh

是出现网络连接失败的提示框吗？可以尝试换一个稳定一点的代理。

**Comment by DULPALAMAKUMBURA** [comment]
Yes same problem here. I am over 16K tokens when the problem arises for me. I can save the conversation and delete some lines and continue the conversation but it never lets to continue over 16K tokens. Any fix?
