### ISSUE TITLE
运行的过程中碰到这个错误：OSError: [WinError 64] 指定的网络名不再可用 

### ISSUE THREAD

**Issue by Acidness** [juzeon/SydneyQt#17]
刚开始用的时候没问题，成功地和Sydney交流了几次，但是到了第三次打开程序，给ai发送消息就报错了
![屏幕截图 2023-05-31 173151](https://github.com/juzeon/SydneyQt/assets/36684248/18ee5853-daeb-491c-8075-bca9ad6f8f4e)

当时的截图
![屏幕截图 2023-05-31 194551](https://github.com/juzeon/SydneyQt/assets/36684248/ec5b011e-95f1-46cb-93da-91c95e8a200d)

不知道是不是自己网的缘故，试了下interestingDarkness的，也是用了几次出现同样的错误

报错的代码
```
Traceback (most recent call last):
  File "D:\Python310\lib\asyncio\windows_events.py", line 485, in finish_recv
    return ov.getresult()
OSError: [WinError 64] 指定的网络名不再可用。

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\Python310\lib\asyncio\proactor_events.py", line 282, in _loop_reading
    length = fut.result()
  File "D:\Python310\lib\site-packages\qasync\_windows.py", line 43, in _process_events
    value = callback(transferred, key, ov)
  File "D:\Python310\lib\asyncio\windows_events.py", line 489, in finish_recv
    raise ConnectionResetError(*exc.args)
ConnectionResetError: [WinError 64] 指定的网络名不再可用。

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "D:\Python310\lib\site-packages\httpcore\_exceptions.py", line 8, in map_exceptions
    yield
  File "D:\Python310\lib\site-packages\httpcore\backends\asyncio.py", line 72, in start_tls
    raise exc
  File "D:\Python310\lib\site-packages\httpcore\backends\asyncio.py", line 63, in start_tls
    ssl_stream = await anyio.streams.tls.TLSStream.wrap(
  File "D:\Python310\lib\site-packages\anyio\streams\tls.py", line 122, in wrap
    await wrapper._call_sslobject_method(ssl_object.do_handshake)
  File "D:\Python310\lib\site-packages\anyio\streams\tls.py", line 137, in _call_sslobject_method
    data = await self.transport_stream.receive()
  File "D:\Python310\lib\site-packages\anyio\_backends\_asyncio.py", line 1274, in receive
    raise self._protocol.exception
anyio.BrokenResourceError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\Python310\lib\site-packages\httpx\_transports\default.py", line 60, in map_httpcore_exceptions
    yield
  File "D:\Python310\lib\site-packages\httpx\_transports\default.py", line 353, in handle_async_request
    resp = await self._pool.handle_async_request(req)
  File "D:\Python310\lib\site-packages\httpcore\_async\connection_pool.py", line 253, in handle_async_request
    raise exc
  File "D:\Python310\lib\site-packages\httpcore\_async\connection_pool.py", line 237, in handle_async_request
    response = await connection.handle_async_request(request)
  File "D:\Python310\lib\site-packages\httpcore\_async\connection.py", line 86, in handle_async_request
    raise exc
  File "D:\Python310\lib\site-packages\httpcore\_async\connection.py", line 63, in handle_async_request
    stream = await self._connect(request)
  File "D:\Python310\lib\site-packages\httpcore\_async\connection.py", line 150, in _connect
    stream = await stream.start_tls(**kwargs)
  File "D:\Python310\lib\site-packages\httpcore\backends\asyncio.py", line 60, in start_tls
    with map_exceptions(exc_map):
  File "D:\Python310\lib\contextlib.py", line 153, in __exit__
    self.gen.throw(typ, value, traceback)
  File "D:\Python310\lib\site-packages\httpcore\_exceptions.py", line 12, in map_exceptions
    raise to_exc(exc)
httpcore.ConnectError

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "D:\新建文件夹 (3)\SydneyQt-master\SydneyQt-master\main.py", line 298, in send_message
    chatbot = await Chatbot.create(cookies=cookies, proxy=proxy if proxy != "" else None)
  File "D:\Python310\lib\site-packages\EdgeGPT.py", line 642, in create
    await _Conversation.create(self.cookies, self.proxy),
  File "D:\Python310\lib\site-packages\EdgeGPT.py", line 386, in create
    response = await client.get(
  File "D:\Python310\lib\site-packages\httpx\_client.py", line 1729, in get
    return await self.request(
  File "D:\Python310\lib\site-packages\httpx\_client.py", line 1506, in request
    return await self.send(request, auth=auth, follow_redirects=follow_redirects)
  File "D:\Python310\lib\site-packages\httpx\_client.py", line 1593, in send
    response = await self._send_handling_auth(
  File "D:\Python310\lib\site-packages\httpx\_client.py", line 1621, in _send_handling_auth
    response = await self._send_handling_redirects(
  File "D:\Python310\lib\site-packages\httpx\_client.py", line 1658, in _send_handling_redirects
    response = await self._send_single_request(request)
  File "D:\Python310\lib\site-packages\httpx\_client.py", line 1695, in _send_single_request
    response = await transport.handle_async_request(request)
  File "D:\Python310\lib\site-packages\httpx\_transports\default.py", line 352, in handle_async_request
    with map_httpcore_exceptions():
  File "D:\Python310\lib\contextlib.py", line 153, in __exit__
    self.gen.throw(typ, value, traceback)
  File "D:\Python310\lib\site-packages\httpx\_transports\default.py", line 77, in map_httpcore_exceptions
    raise mapped_exc(message) from exc
httpx.ConnectError
```
请大佬指导

**Comment by Acidness** [comment]
![屏幕截图 2023-05-31 173151](https://github.com/juzeon/SydneyQt/assets/36684248/2e2ddafe-447d-4dcb-95b7-a3431653d27f)
zhe

**Comment by Acidness** [comment]
`Traceback (most recent call last):
  File "D:\Python310\lib\asyncio\windows_events.py", line 485, in finish_recv
    return ov.getresult()
OSError: [WinError 64] 指定的网络名不再可用。

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\Python310\lib\asyncio\proactor_events.py", line 282, in _loop_reading
    length = fut.result()
  File "D:\Python310\lib\site-packages\qasync\_windows.py", line 43, in _process_events
    value = callback(transferred, key, ov)
  File "D:\Python310\lib\asyncio\windows_events.py", line 489, in finish_recv
    raise ConnectionResetError(*exc.args)
ConnectionResetError: [WinError 64] 指定的网络名不再可用。

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "D:\Python310\lib\site-packages\httpcore\_exceptions.py", line 8, in map_exceptions
    yield
  File "D:\Python310\lib\site-packages\httpcore\backends\asyncio.py", line 72, in start_tls
    raise exc
  File "D:\Python310\lib\site-packages\httpcore\backends\asyncio.py", line 63, in start_tls
    ssl_stream = await anyio.streams.tls.TLSStream.wrap(
  File "D:\Python310\lib\site-packages\anyio\streams\tls.py", line 122, in wrap
    await wrapper._call_sslobject_method(ssl_object.do_handshake)
  File "D:\Python310\lib\site-packages\anyio\streams\tls.py", line 137, in _call_sslobject_method
    data = await self.transport_stream.receive()
  File "D:\Python310\lib\site-packages\anyio\_backends\_asyncio.py", line 1274, in receive
    raise self._protocol.exception
anyio.BrokenResourceError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\Python310\lib\site-packages\httpx\_transports\default.py", line 60, in map_httpcore_exceptions
    yield
  File "D:\Python310\lib\site-packages\httpx\_transports\default.py", line 353, in handle_async_request
    resp = await self._pool.handle_async_request(req)
  File "D:\Python310\lib\site-packages\httpcore\_async\connection_pool.py", line 253, in handle_async_request
    raise exc
  File "D:\Python310\lib\site-packages\httpcore\_async\connection_pool.py", line 237, in handle_async_request
    response = await connection.handle_async_request(request)
  File "D:\Python310\lib\site-packages\httpcore\_async\connection.py", line 86, in handle_async_request
    raise exc
  File "D:\Python310\lib\site-packages\httpcore\_async\connection.py", line 63, in handle_async_request
    stream = await self._connect(request)
  File "D:\Python310\lib\site-packages\httpcore\_async\connection.py", line 150, in _connect
    stream = await stream.start_tls(**kwargs)
  File "D:\Python310\lib\site-packages\httpcore\backends\asyncio.py", line 60, in start_tls
    with map_exceptions(exc_map):
  File "D:\Python310\lib\contextlib.py", line 153, in __exit__
    self.gen.throw(typ, value, traceback)
  File "D:\Python310\lib\site-packages\httpcore\_exceptions.py", line 12, in map_exceptions
    raise to_exc(exc)
httpcore.ConnectError

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "D:\新建文件夹 (3)\SydneyQt-master\SydneyQt-master\main.py", line 298, in send_message
    chatbot = await Chatbot.create(cookies=cookies, proxy=proxy if proxy != "" else None)
  File "D:\Python310\lib\site-packages\EdgeGPT.py", line 642, in create
    await _Conversation.create(self.cookies, self.proxy),
  File "D:\Python310\lib\site-packages\EdgeGPT.py", line 386, in create
    response = await client.get(
  File "D:\Python310\lib\site-packages\httpx\_client.py", line 1729, in get
    return await self.request(
  File "D:\Python310\lib\site-packages\httpx\_client.py", line 1506, in request
    return await self.send(request, auth=auth, follow_redirects=follow_redirects)
  File "D:\Python310\lib\site-packages\httpx\_client.py", line 1593, in send
    response = await self._send_handling_auth(
  File "D:\Python310\lib\site-packages\httpx\_client.py", line 1621, in _send_handling_auth
    response = await self._send_handling_redirects(
  File "D:\Python310\lib\site-packages\httpx\_client.py", line 1658, in _send_handling_redirects
    response = await self._send_single_request(request)
  File "D:\Python310\lib\site-packages\httpx\_client.py", line 1695, in _send_single_request
    response = await transport.handle_async_request(request)
  File "D:\Python310\lib\site-packages\httpx\_transports\default.py", line 352, in handle_async_request
    with map_httpcore_exceptions():
  File "D:\Python310\lib\contextlib.py", line 153, in __exit__
    self.gen.throw(typ, value, traceback)
  File "D:\Python310\lib\site-packages\httpx\_transports\default.py", line 77, in map_httpcore_exceptions
    raise mapped_exc(message) from exc
httpx.ConnectError`

**Comment by juzeon** [comment]
这个是典型的网络问题，请尝试通过以下方式解决：
- 在Settings中设置代理
  - 使用HTTP代理，例如 http://127.0.0.1:7890
  - 使用socks5代理，例如 socks5h://127.0.0.1:7890 （socks5后面跟着的h代表使用远端服务器进行域名解析）
- 在Settings中将代理置空，然后使用Proxifier配置代理

**Comment by Acidness** [comment]
> 这个是典型的网络问题，请尝试通过以下方式解决：
> 
> * 在Settings中设置代理
>   
>   * 使用HTTP代理，例如 http://127.0.0.1:7890
>   * 使用socks5代理，例如 socks5h://127.0.0.1:7890 （socks5后面跟着的h代表使用远端服务器进行域名解析）
> * 在Settings中将代理置空，然后使用Proxifier配置代理

感谢，问题已经解决
