### ISSUE TITLE
Throttled: Request is throttled.

### ISSUE THREAD

**Issue by JnXYG** [juzeon/SydneyQt#18]
你好，作者！你的作品是我安装的第一个github上的项目，而且功能十分全面，非常感谢。我最近在使用时出现了以下报错 Throttled: Request is throttled.无法继续进行对话。我的cookies.json按照要求进行了编辑，且安装了Edgegpt0.6.5。我测试了网页版newbing并且切换了多个账号，它们都可以正常对话。在命令指示符中，它显示了以下内容：
C:\Users\10172\Desktop\SydneyQt-master>python main.py
Traceback (most recent call last):
  File "C:\Users\10172\Desktop\SydneyQt-master\main.py", line 380, in send_message
    await stream_output()
  File "C:\Users\10172\Desktop\SydneyQt-master\main.py", line 318, in stream_output
    async for final, response in chatbot.ask_stream(
  File "C:\Users\10172\AppData\Roaming\Python\Python311\site-packages\EdgeGPT.py", line 676, in ask_stream
    async for response in self.chat_hub.ask_stream(
  File "C:\Users\10172\AppData\Roaming\Python\Python311\site-packages\EdgeGPT.py", line 567, in ask_stream
    raise Exception(
Exception: Throttled: Request is throttled.
请问我应该如何解决？

**Comment by JnXYG** [comment]
我最近在使用时出现了以下报错 Throttled: Request is throttled.无法继续进行对话。我的config.json按照要求进行了编辑，且安装了Edgegpt0.6.5。在

**Comment by JnXYG** [comment]
在安装依赖项的过程中edgegpt的安装会出现以下黄字  
WARNING: The scripts edge-gpt-image.exe and edge-gpt.exe are installed in 'C:\Users\10172\AppData\Roaming\Python\Python311\Scripts' which is not on PATH.
  Consider adding this directory to PATH or, if you prefer to suppress this warning, use --no-warn-script-location.
不知道这是否会有些帮助。

**Comment by JnXYG** [comment]
你好，问题好像自己解决了。不知道是不是因为我删除所有SydneyQt和依赖项内容重新安装了最新版本的原因，从6/3的1:00左右出现的Throttled: Request is throttled的问题，在6/3 13:38不再出现了。
谢谢你一直以来维护这个作品🙏

**Comment by JnXYG** [comment]
close with comment
