### ISSUE TITLE
TypeError: 'type' object is not subscriptable

### ISSUE THREAD

**Issue by PlayMcBKuwu** [juzeon/SydneyQt#25]
```python
Traceback (most recent call last):
  File "main.py", line 716, in <module>
    gui = SydneyWindow(Config())
  File "main.py", line 217, in __init__
    workspace_names = list[str](self.workspace_dict.keys())
TypeError: 'type' object is not subscriptable
```

**Comment by juzeon** [comment]
请使用Python 3.10及以上版本。
