### ISSUE TITLE
提示Authentication failed，重新替换cookie无效

### ISSUE THREAD

**Issue by jlthkf22** [juzeon/SydneyQt#36]
Traceback (most recent call last):
  File "E:\SydneyQt-master\main.py", line 410, in send_sydney
    chatbot = await Chatbot.create(cookies=cookies, proxy=proxy if proxy != "" else None)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\SydneyQt-master\EdgeGPT.py", line 708, in create
    await _Conversation.create(self.proxy, cookies=cookies),
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\SydneyQt-master\EdgeGPT.py", line 485, in create
    raise Exception("Authentication failed")
Exception: Authentication failed

**Comment by juzeon** [comment]
Duplicate of #26
