### ISSUE TITLE
Cannot connect to host https:443 ssl:default [None]

### ISSUE THREAD

**Issue by JayGarland** [juzeon/SydneyQt#50]
still unable to connect and start a talk after trying added worker wss adress from cloudflare, anyone know how to solve it? at the same time, it seems Bing has been tightened control that now I can only access it in edge through official site?

**Comment by juzeon** [comment]
Hello. Did this problem occur recently? Could you please provide the `Wss Domain` value of your settings and the complete output of the error message?

**Comment by JayGarland** [comment]
yes here's my wss domain: https://sydneybot.mamba579jpy.workers.dev/, and here's the message in command line: 
Traceback (most recent call last):
  File "D:\Python311\Lib\site-packages\aiohttp\connector.py", line 1152, in _create_direct_connection
    hosts = await asyncio.shield(host_resolved)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Python311\Lib\site-packages\aiohttp\connector.py", line 874, in _resolve_host
    addrs = await self._resolver.resolve(host, port, family=self._family)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Python311\Lib\site-packages\aiohttp\resolver.py", line 33, in resolve
    infos = await self._loop.getaddrinfo(
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Python311\Lib\asyncio\base_events.py", line 867, in getaddrinfo
    return await self.run_in_executor(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Python311\Lib\site-packages\qasync\__init__.py", line 150, in run
    r = callback(*args, **kwargs)
        ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Python311\Lib\socket.py", line 962, in getaddrinfo
    for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
socket.gaierror: [Errno 11001] getaddrinfo failed

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\Jay_Yu\Desktop\mod_gpt\SydneyQt\main.py", line 528, in send_sydney
    await stream_output()
  File "C:\Users\Jay_Yu\Desktop\mod_gpt\SydneyQt\main.py", line 452, in stream_output
    async for response in agen:
  File "C:\Users\Jay_Yu\Desktop\mod_gpt\SydneyQt\sydney.py", line 262, in ask_stream
    async with session.ws_connect(
  File "D:\Python311\Lib\site-packages\aiohttp\client.py", line 1141, in __aenter__
    self._resp = await self._coro
                 ^^^^^^^^^^^^^^^^
  File "D:\Python311\Lib\site-packages\aiohttp\client.py", line 779, in _ws_connect
    resp = await self.request(
           ^^^^^^^^^^^^^^^^^^^
  File "D:\Python311\Lib\site-packages\aiohttp\client.py", line 536, in _request
    conn = await self._connector.connect(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Python311\Lib\site-packages\aiohttp\connector.py", line 540, in connect
    proto = await self._create_connection(req, traces, timeout)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Python311\Lib\site-packages\aiohttp\connector.py", line 901, in _create_connection
    _, proto = await self._create_direct_connection(req, traces, timeout)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Python311\Lib\site-packages\aiohttp\connector.py", line 1166, in _create_direct_connection
    raise ClientConnectorError(req.connection_key, exc) from exc
aiohttp.client_exceptions.ClientConnectorError: Cannot connect to host https:443 ssl:default [getaddrinfo failed]

**Comment by JayGarland** [comment]
> Hello. Did this problem occur recently? Could you please provide the `Wss Domain` value of your settings and the complete output of the error message?

yes here's my wss domain: https://sydneybot.mamba579jpy.workers.dev/, and here's the message in command line:
Traceback (most recent call last):
File "D:\Python311\Lib\site-packages\aiohttp\connector.py", line 1091, in _start_tls_connection
tls_transport = await self._loop.start_tls(
^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "D:\Python311\Lib\asyncio\base_events.py", line 1267, in start_tls
await waiter
File "D:\Python311\Lib\asyncio\sslproto.py", line 574, in _on_handshake_complete
raise handshake_exc
ConnectionResetError

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
File "C:\Users\Jay_Yu\Desktop\mod_gpt\SydneyQt\main.py", line 528, in send_sydney
await stream_output()
File "C:\Users\Jay_Yu\Desktop\mod_gpt\SydneyQt\main.py", line 452, in stream_output
async for response in agen:
File "C:\Users\Jay_Yu\Desktop\mod_gpt\SydneyQt\sydney.py", line 262, in ask_stream
async with session.ws_connect(
File "D:\Python311\Lib\site-packages\aiohttp\client.py", line 1141, in aenter
self._resp = await self._coro
^^^^^^^^^^^^^^^^
File "D:\Python311\Lib\site-packages\aiohttp\client.py", line 779, in _ws_connect
resp = await self.request(
^^^^^^^^^^^^^^^^^^^
File "D:\Python311\Lib\site-packages\aiohttp\client.py", line 536, in _request
conn = await self._connector.connect(
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "D:\Python311\Lib\site-packages\aiohttp\connector.py", line 540, in connect
proto = await self._create_connection(req, traces, timeout)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "D:\Python311\Lib\site-packages\aiohttp\connector.py", line 899, in _create_connection
_, proto = await self._create_proxy_connection(req, traces, timeout)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "D:\Python311\Lib\site-packages\aiohttp\connector.py", line 1325, in _create_proxy_connection
return await self._start_tls_connection(
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "D:\Python311\Lib\site-packages\aiohttp\connector.py", line 1111, in _start_tls_connection
raise client_error(req.connection_key, exc) from exc
aiohttp.client_exceptions.ClientConnectorError: Cannot connect to host https:443 ssl:default [None]

**Comment by juzeon** [comment]
`Wss Domain` requires a domain name, not a URL. You should type `sydneybot.mamba579jpy.workers.dev` instead of `https://sydneybot.mamba579jpy.workers.dev/`.

**Comment by JayGarland** [comment]
> `Wss Domain` requires a domain name, not a URL. You should type `sydneybot.mamba579jpy.workers.dev` instead of `https://sydneybot.mamba579jpy.workers.dev/`.

ohhh thanks my life saver!

**Comment by JayGarland** [comment]
okay just in case leave a note for the wss domain setting, I though it was the URL while in the setting it doesn't specify what to input..
