### ISSUE TITLE
Attempt to decode JSON with unexpected mimetype: ', url=URL('https://edgeservices.bing.com/edgesvc/turing/conversation/create')  

### ISSUE THREAD

**Issue by QiranYC** [juzeon/SydneyQt#86]
Traceback (most recent call last):
  File "C:\Users\Administrator\Desktop\yuni_dev\SydneyQt-master\SydneyQt-master\sydney.py", line 225, in create_conversation
    conversation = await response.json()
                   ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python311\Lib\site-packages\aiohttp\client_reqrep.py", line 1104, in json
    raise ContentTypeError(
aiohttp.client_exceptions.ContentTypeError: 0, message='Attempt to decode JSON with unexpected mimetype: ', url=URL('https://edgeservices.bing.com/edgesvc/turing/conversation/create')

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Administrator\Desktop\yuni_dev\SydneyQt-master\SydneyQt-master\main.py", line 441, in send_sydney
    conversation = await sydney.create_conversation(cookies=cookies, proxy=proxy if proxy != "" else None)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Administrator\Desktop\yuni_dev\SydneyQt-master\SydneyQt-master\sydney.py", line 228, in create_conversation
    raise Exception(text)
Exception

设置proxy后仍然报错

**Comment by juzeon** [comment]
说实话这种错误都是代理的问题，不行就多试几个节点。
