### ISSUE TITLE
0, message='', url=URL('https://edgeservices.bing.com/edgesvc/turing/conversation/create')

### ISSUE THREAD

**Issue by xiaozhanniyaozhengqia** [juzeon/SydneyQt#91]
检查过newbing可用，已设置cookies.json和cloudflare。

**Comment by xiaozhanniyaozhengqia** [comment]
E:\code\qtcode\SydneyQt>python main.py                                                                                  
Traceback (most recent call last):                                                                                        
File "E:\code\qtcode\SydneyQt\main.py", line 453, in send_sydney                                                          
conversation = await sydney.create_conversation(cookies=cookies, proxy=proxy if proxy != "" else None)                
File "E:\code\qtcode\SydneyQt\sydney.py", line 225, in create_conversation                                                
response = await session.get(                                                                                         
File "C:\Python310\lib\site-packages\aiohttp\client.py", line 588, in _request                                            
raise TooManyRedirects(                                                                                             
aiohttp.client_exceptions.TooManyRedirects: 0, message='', url=URL('https://edgeservices.bing.com/edgesvc/turing/conversation/create')

**Comment by xiaozhanniyaozhengqia** [comment]
解决了，原来是要在客户端settings的proxy里填入代理地址。
可以是HTTP代理地址也可以是SOCKS5代理地址。
HTTP代理地址通常是 http://<主机名>:<端口号>。主机名是代理服务器的IP地址或域名，而端口号是用于连接代理服务器的端口。例如，http://127.0.0.1:7890 是一个HTTP代理地址的示例。

我用的是Sakuracat，可以在个人界面看到端口号，用实际的端口号替换http://127.0.0.1:7890中的7890就可以运行了
